### PR TITLE
adjust old test with weird difference

### PR DESCRIPTION
**Pull request by gordon**
In preparation for #20.

### CODE REVIEW

**Comment by satta** [comment]
I assume the new reference file in gthtestdata already exists.

**Review by satta — APPROVED** [review]
Are the statically compiled binaries going to be added to the release page?

**Comment by gordon** [comment]
> I assume the new reference file in gthtestdata already exists.

Yes, I added it. `gthtestdata` is the old repo we couldn't add to GitHub because it's too large.

**Comment by gordon** [comment]
> Are the statically compiled binaries going to be added to the release page?

I was planning to add it to https://genomethreader.org/download.html with the 1.7.4 release (it changes Linux 64-bit to statically linked only). But we can also add it here on GitHub then.
But we can also add it here as well then.

**Pull request merged**
